name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      FC: gfortran
      GCC_V: 9

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gnuplot and gfortran
      run: |
        sudo apt install -y gnuplot
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${GCC_V}

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        format: 'YYYY-MM'

    - name: Setup cache for stack to speed up fpm build
      id: cache
      uses: actions/cache@v2
      with:
        path: "/home/runner/.stack/"
        key: ${{ steps.time.outputs.time }}

    - name: Install fpm
      run: |
        git init fpm
        git -C fpm fetch https://github.com/fortran-lang/fpm.git ffd95a4179276d49fd4d2a277c2eba905dc43b7a
        git -C fpm checkout -qf FETCH_HEAD
        cd fpm/bootstrap
        stack build
        stack install

    - name: put fpm to PATH
      run: |
          sudo cp /home/runner/.local/bin/fpm /usr/local/bin

    - name: Build
      run: fpm build

    - name: Run tests
      run: fpm test

    - name: Generate Graphs
      run: ./generate_graphs.sh
